/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color Palette
        'tertiary-fixed': '#e0e3e5',
        'on-primary-fixed-variant': '#474747',
        'on-error-container': '#93000a',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-primary': '#c6c6c6',
        'on-surface-variant': '#4c4546',
        'on-secondary-fixed': '#002113',
        'on-background': '#1b1b1b',
        'on-primary-fixed': '#1b1b1b',
        'surface-dim': '#dadada',
        'on-tertiary-fixed-variant': '#444749',
        'on-tertiary-container': '#818486',
        'primary-fixed-dim': '#c6c6c6',
        'primary-container': '#1b1b1b',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'on-secondary': '#ffffff',
        'primary-fixed': '#e2e2e2',
        'on-secondary-fixed-variant': '#005236',
        'outline': '#7e7576',
        'surface-container-high': '#e8e8e8',
        'on-tertiary': '#ffffff',
        'tertiary': '#000000',
        'on-primary-container': '#848484',
        'surface-bright': '#f9f9f9',
        'primary': '#000000',
        'surface': '#f9f9f9',
        'background': '#f9f9f9',
        'inverse-on-surface': '#f1f1f1',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'error': '#ba1a1a',
        'surface-container': '#eeeeee',
        'on-surface': '#1b1b1b',
        'secondary-fixed-dim': '#4edea3',
        'outline-variant': '#cfc4c5',
        'tertiary-container': '#191c1e',
        'secondary': '#006c49',
        'error-container': '#ffdad6',
        'secondary-fixed': '#6ffbbe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container-highest': '#e2e2e2',
        'inverse-surface': '#303030',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'sm': '8px',
        'xs': '4px',
        'xl': '24px',
        'lg': '16px',
        'md': '12px',
        'xxl': '32px',
      },
      fontFamily: {
        'h2': ['Inter'],
        'body-sm': ['Inter'],
        'caption': ['Inter'],
        'body': ['Inter'],
        'h1': ['Inter'],
      },
      fontSize: {
        'h2': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'h1': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}